### ISSUE TITLE
[DOC] Missing Aqueduct to Conduit migration guide

### ISSUE THREAD

**Issue by tbarbette** [conduit-dart/conduit#103]
Hi all,

This page about migrating from aqueduct,  which is referenced here and there appears to be dead : https://gitbook.theconduit.dev/migration_guide

Can you provide the migration guide and maybe arrange a redirection?

Thanks

**Comment by j4qfrost** [comment]
For the most part it should be a drop in replacement, if you have any specific questions, message me on discord frosty#1337 or email me j4qfrost@gmail.com. I haven't had a chance to do an extensive dog-fooding of the library from a production perspective using an old aqueduct project. Sorry for the late response, I realize you have likely moved on.
