### ISSUE TITLE
Broken links within README 

### ISSUE THREAD

**Issue by MarkOSullivan94** [conduit-dart/conduit#104]
**Describe the bug**

The hyperlinks for '[Install Dart](https://www.dartlang.org/install)' and 'Our main docs live [here](https://gitbook.theconduit.dev/contributing)' do not work

**To Reproduce**
1. Go to README for the project
2. Click on both hyperlinks
3. Neither will load the proper webpage

**Expected behavior**

The correct web pages are displayed

**Comment by j4qfrost** [comment]
going to rework documentation completely
