### ISSUE TITLE
[BUG] error when Isolates cannot be started up

### ISSUE THREAD

**Issue by renatoathaydes** [conduit-dart/conduit#108]
**Describe the bug**

Inside the `Application.start` method, when there's a `TimeoutException` due to a failure to start an Isolate, the server will be stopped using this code:

```dart
    } catch (e, st) {
      logger.severe("$e", this, st);
      await stop().timeout(const Duration(seconds: 5));
      rethrow;
    }
```

This, however, fails on the call to `stop()` because of this error:

```
LateInitializationError: Field '_serverSendPort@884428277' has not been initialized.
#0      ApplicationIsolateSupervisor._serverSendPort (package:conduit/src/application/isolate_supervisor.dart)
#1      ApplicationIsolateSupervisor.stop (package:conduit/src/application/isolate_supervisor.dart:70:5)
```

**To Reproduce**

Run this code (and please tell me why does it fail to start up isolates??):

```
import 'dart:io';
import 'package:conduit/conduit.dart' as conduit;

void main() {
  runConduitServer(Platform.numberOfProcessors);
}

void runConduitServer(int cores) async {
  final app = conduit.Application<_StaticBenchmarkChannel>()
    ..options.address = InternetAddress.anyIPv6
    ..options.port = 8080;

  await app.start(numberOfInstances: cores);
}

class _StaticBenchmarkChannel extends conduit.ApplicationChannel {
  @override
  conduit.Controller get entryPoint {
    final router = conduit.Router();

    router
        .route("/")
        .linkFunction((request) async => conduit.Response.ok('Hello World!\n'));

    return router;
  }
}
```

**Expected behavior**

This exception should not occur even when  an Isolate fails to start (why it failed to start is a separate problem... it might be due to the fact I have no config file? Should I file a separate bug for reporting that, if so?).

**Comment by renatoathaydes** [comment]
Looks like the original error causing Isolates to not startup is this getter trying to access a null field:

```dart
ChannelRuntimeImpl ... {
  @override
  Type get channelType => type!.reflectedType;
...
}
```

**Comment by renatoathaydes** [comment]
Oh I get it... Conduit is trying to use Dart mirrors to access the `ApplicationChannel` class.
As that's private , it can't... so things break.

I think it would be a good idea to detect this problem and report the appropriate error?

**Comment by andresruizdev** [comment]
Hello @renatoathaydes, sorry for late response.

Your problem is ocurring cause your **`AplicationChannel`** class is private and it should be public. This is causing that counduit checks some nullable instances which are not initialized or cannot manipulate (Conduit cannot manipulate `_StaticBenchmarkChannel` itself).

Try again with the same example that you posted before but using a public **`ApplicationChannel`** and everything should work fine.

```
import 'package:conduit/conduit.dart' as conduit;

void main() {
  runConduitServer(Platform.numberOfProcessors);
}

void runConduitServer(int cores) async {
  final app = conduit.Application<StaticBenchmarkChannel>()
    ..options.address = InternetAddress.anyIPv6
    ..options.port = 8080;

  await app.start(numberOfInstances: cores);
}

class StaticBenchmarkChannel extends conduit.ApplicationChannel {
  @override
  conduit.Controller get entryPoint {
    final router = conduit.Router();

    router
        .route("/")
        .linkFunction((request) async => conduit.Response.ok('Hello World!\n'));

    return router;
  }
}
```
**My test result**

![image](https://user-images.githubusercontent.com/29277715/186519243-0200d9b9-654b-4110-8ab0-d4b82c21c69f.png)

**Comment by renatoathaydes** [comment]
@andresruizdev I think you may have missed my previous message.

**Comment by andresruizdev** [comment]
> @andresruizdev I think you may have missed my previous message.

Damn... You're right @renatoathaydes, I focused only on the problem. My bad, sorry. 

> Oh I get it... Conduit is trying to use Dart mirrors to access the `ApplicationChannel` class. As that's private , it can't... so things break.
> 
> I think it would be a good idea to detect this problem and report the appropriate error?

I think that the [dart:mirros library](https://api.dart.dev/stable/2.17.6/dart-mirrors/dart-mirrors-library.html) will be a good point to start an contribute to prevent this problem. This library have a class called `ClassMirror`, I don't know if it have any property to check the use of private classes in `ApplicationChannel`

**Comment by andresruizdev** [comment]
Hello, I was just coding a little and I think that I made some progress (In a private and clean project for now.).

ClassMirror works to detect if the class passed as `Type`, is private or not. I'm reading the `Application` Class source code from Conduit to verify how to add this.

### My Test
**When a private class is passed as Type:**
![image](https://user-images.githubusercontent.com/29277715/186965704-97ae9ddd-b0c5-450c-9c87-99d721b33720.png)

**When a public class is passed as Type:**
![image](https://user-images.githubusercontent.com/29277715/186966024-fd112985-f5b7-43b8-8358-18c24d964963.png)
