### ISSUE TITLE
[BUG] No ApplicationChannel subclass found in bscan/bscan : Package file 'file:///root/bscaschan.nofifty.one/.packages' not found. Run 'pub get' and retry.

### ISSUE THREAD

**Issue by justintim-es** [conduit-dart/conduit#111]
in the past i could upload my conduit application and name it to whatever on github running pub get once and voila conduit build works too. Since i dont know when i get the following error when i try to run conduit build i have run pub get but nothing happens. Also not when i name the package to bscan

**Comment by pro100svitlo** [comment]
same problem

**Comment by dm-ra-01** [comment]
This is a result of a breaking change in Dart and breaks many of Conduit's CLI commands eg. conduit build, conduit serve. 
Reference: https://github.com/dart-lang/sdk/issues/48272

To help the dev team on their way, there are two fixes which may help: 
Option 1:  Change the string from .packages to the new json file

packages/conduit/lib/src/cli/mixins/project.dart

Replace:   
`Uri get packageConfigUri => projectDirectory!.uri.resolve(".packages");`
with
`  Uri? get packageConfigUri =>
      projectDirectory!.uri.resolve(".dart_tool/package_config.json");`

packages/runtime/lib/src/build_manager.dart
Line 58, replace: 
`packageConfigURI: sourceDirectoryUri.resolve(".packages"),`
with
`packageConfigURI:   sourceDirectoryUri.resolve(".dart_tool/package_config.json"),`

Similar changes needed to any other file referencing .packages eg. packages/conduit/lib/src/cli/commands/serve.dart and test packages.

This change has been tested and resolved the issue. I just can't identify if it is the most elegant fix.

Option 2: Implement Dart package_config , an official Dart package: https://pub.dev/packages/package_config

Thanks everyone for your hard work with Conduit

**Comment by Rodsevich** [comment]
Can't you make a PR with this fix, @dm-ra-01, please?

**Comment by amine-zergan** [comment]
still same problem, with those upgrades !
Uncaught error
    Bad state: Package file 'file:///*.*/.packages' not found. Run 'pub get' and retry.,

**Comment by dm-ra-01** [comment]
> Can you make a PR with this fix, @dm-ra-01, please?

Argh, so sorry for missing this or I would have been happy to. I see there has been a push 23hrs ago already. Let me know if you need more from me and I'll see what I can do.

**Comment by amine-zergan** [comment]
issue resolved by :
first update line :
Replace:
Uri get packageConfigUri => projectDirectory!.uri.resolve(".packages");
with
Uri? get packageConfigUri => projectDirectory!.uri.resolve(".dart_tool/package_config.json");
after make this change , run dart pub global activate conduit

**Comment by kbaylosis** [comment]
Without changing anything in the conduit code, you can do this temporarily until a proper fix/PR is applied.

On your project root directory:
```
ln -s .dart_tool/package_config.json .packages
```

Find and change this in your package_config.json:
```
{
      "name": "<YOUR PROJECT'S NAME>",
      "rootUri": "../",
      "packageUri": "lib/",
      "languageVersion": "2.12"
}
```
to
```
{
      "name": "<YOUR PROJECT'S NAME>",
      "rootUri": ".",
      "packageUri": "lib/",
      "languageVersion": "2.12"
}
```

NOTE: You have to re-apply this every time you run a ```dart pub get```.

**Comment by j4qfrost** [comment]
Fixed with the latest release
