### ISSUE TITLE
[BUG] When running `conduit db validate` I get an *Invalid Migration file* error

### ISSUE THREAD

**Issue by juanaguss** [conduit-dart/conduit#122]
Hello! I recently updated Conduit and since then I can not alter the database schema using `conduit db validate`. I tried downgrading Conduit and playing with the dependency versions but nothing worked. I'm using Conduit 3.2.2 and Dart 2.18.3.

![image](https://user-images.githubusercontent.com/50247833/197635604-bbaf95c1-3324-4925-90f0-41d1bb3a7f63.png)

Does anybody know how to solve this? Thank you in advance!

**Comment by Rodsevich** [comment]
plese take a look!

**Comment by petrovyuri** [comment]
Такая проблема только на Windows. (

**Comment by petrovyuri** [comment]
Version 3.2.5 is also a problem. 
![image](https://user-images.githubusercontent.com/48598325/197947414-08bcc2a9-9002-49f5-ac0a-ad3f518238cb.png)

System: Windows 11
Flutter: 3.3.5
Dart SDK: 2.18.2

**Comment by suxoikorm** [comment]
I have same error on **macOS** on all of this commands:
```
conduit db generate
conduit db validate
conduit db upgrade
```

<img width="996" alt="Снимок экрана 2022-11-09 в 01 22 32" src="https://user-images.githubusercontent.com/17691118/200678216-a8128ef3-ef9f-42a1-89da-47608f6cfac1.png">

Dart SDK: 2.18.4
Conduit 3.2.9

**Comment by MansonLuo** [comment]
meet same error

**Comment by petrovyuri** [comment]
@juanaguss @suxoikorm @Rodsevich In the new version of Conduit 3.2.10, the problem has been solved
