### ISSUE TITLE
[BUG] Docs link not working

### ISSUE THREAD

**Issue by Peter-Noble** [conduit-dart/conduit#123]
Clicking on the Docs button on the website home screen doesn't take you anywhere.  Going directly to https://gitbook.theconduit.dev/ also doesn't respond.  I've tried this across multiple browsers, devices and network connections.

**Comment by petrovyuri** [comment]
Hello. Here is a working link https://j4qfrost.gitbook.io/conduit/

**Comment by j4qfrost** [comment]
Fixed on README
