### ISSUE TITLE
Rethink the name "conduit"

### ISSUE THREAD

**Issue by MaSimm** [conduit-dart/conduit#13]
Hello,
Sorry if this has already been discussed, I haven't been in any discussion regarding this project.
But as someone from the outside, I'm wondering if "Conduit" is a good name for this project. A quick google search gave these other software projects with the same name:
- https://conduit.rs/
- https://github.com/conduitframework/conduit (it's name is "conduit framework")
- https://en.wikipedia.org/wiki/Conduit_(software)

So it might be unfortunate for search engine optimization and possible confusion with the other conduit framework.

**Comment by Reductions** [comment]
We have already published all packages prefixed with conduit so we are not changing it.
1. `conduit.rs` is interesting but I don't think they will be anything but mildly used.
2. The elixir lib is a dead project that was mostly used by the company that developed it. (I have Elixir background)
3. Is a dead project for almost 6-7 years now.
