### ISSUE TITLE
[BUG] Invalid migration file. Must contain exactly one 'Migration' subclass

### ISSUE THREAD

**Issue by MansonLuo** [conduit-dart/conduit#133]
**Describe the bug**
cannot add some initial datas using migration file at the first time

**To Reproduce**
1. after setup models and create database within postgresql,
2. run cmd: conduit db generate
3. writing code that add entries into database in the migration file.
4. run cmd: conduit db upgrade --connect postgres://heroes_user:Abc@1234@localhost:5432/heroes
5. see the error Invalid migration file. Must contain exactly one 'Migration' subclass. File: '..../projectroot/migrations/00000001_initial.migration.dart'.

**Expected behavior**
adding some entries into database.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  window 10
 - Browser chrome
 - Version: 3.2.9

**Comment by j4qfrost** [comment]
@MansonLuo I've released 3.2.10, can you check that this issue is resolved?

**Comment by petrovyuri** [comment]
I checked on Windows version 3.2.10, everything works fine. Thanks a lot  @j4qfrost

**Comment by MansonLuo** [comment]
everything work fine, all fixed. thank you.

**Comment by MansonLuo** [comment]
all fixed.

**Comment by MansonLuo** [comment]
but, after run cmd 'conduit db upgrade --connect postgres://heroes_user:password@localhost:5432/heroes' from tutorial, it did connectting to sql server, and create the database, but it did't insert initial data defined in seed() method.

and after rerun 'conduit serve', navigate broswer to url '/heroes', it shows me '{"error":"unable to connect to database"}'

i cannot found solutino, maybe it need run connecting db cmd by manully?

**Comment by MansonLuo** [comment]
this is my postgres.
![image](https://user-images.githubusercontent.com/19282278/202103027-e4b5d82f-0372-460e-88fc-91ba6efe90af.png)

**Comment by MansonLuo** [comment]
@j4qfrost

**Comment by MansonLuo** [comment]
it need config.yaml to keep database connection info.

**Comment by MansonLuo** [comment]
close
