### ISSUE TITLE
[BUG] Runtime error while using conduit_test: ^3.2.8

### ISSUE THREAD

**Issue by kbaylosis** [conduit-dart/conduit#140]
**Describe the bug**
Encountered a runtime error while using conduit_test: ^3.2.8

```
*** Uncaught error
    IsolateSpawnException: Unable to spawn isolate: ../../../../../../.pub-cache/hosted/pub.dartlang.org/conduit_test-3.2.8/lib/src/auth_harness.dart:60:42: Error: The argument type 'Type' can't be assigned to the parameter type 'dynamic Function(String)'.
 - 'Type' is from 'dart:core'.
        allowedScopes: allowedScope?.map(AuthScope).toList());
                                         ^
```

**To Reproduce**
1. Add conduit_test: ^3.2.8 in the dev_dependencies
```
dependencies:
    ...
    conduit: ^3.2.9
    conduit_common: ^3.2.8
    conduit_open_api: ^3.2.8
    ...
 
dev_dependencies:
    ...
    conduit_test: ^3.2.8
    test: ^1.22.0
    ...
```
2. Use it in the test harnesses

**Screenshots**
It looks like code released in pub.dev is different from the source.
<img width="795" alt="Screen_Shot_2022-11-12_at_1 23 00_AM" src="https://user-images.githubusercontent.com/1789397/201897105-78a55754-d157-4d50-91f4-a5dd18489237.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1
 - Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_arm64"

**Comment by j4qfrost** [comment]
@kbaylosis can you test and review this after testing on CI passes? https://github.com/conduit-dart/conduit/pull/139

**Comment by MansonLuo** [comment]
you should click debug icon rather that run icon in vscod, or you can run cmd 'dart run test' in terminal under project root path.

**Comment by j4qfrost** [comment]
I am going to go ahead and close this seeing as how #139 is merged.
