### ISSUE TITLE
generate migrate file[BUG]

### ISSUE THREAD

**Issue by amine-zergan** [conduit-dart/conduit#141]
when generate command : conduit db generate , it run emty migration file for database
-- Conduit CLI Version: 3.2.10
-- Conduit project version: 3.2.10
-- The following ManagedObject<T> subclasses were found:
    
    
    * If you were expecting more declarations, ensure the files are visible in the application library file.
    
-- Created new migration file (version 1).

for migration file :

class Migration1 extends Migration { 
  @override
  Future upgrade() async {
   
  }
  
  @override
  Future downgrade() async {}
  
  @override
  Future seed() async {}
}

**Comment by petrovyuri** [comment]
Hi, most likely you need to declare the models in the controller

**Comment by MansonLuo** [comment]
it's something weird, you should defind your model, your modelController, and define corresponding routes in your channel file using just defined model, so it can generate corect migration file when you run cmd 'conduit db generate'.

**Comment by j4qfrost** [comment]
Closing this as comments seem to resolve the issue.
