### ISSUE TITLE
project that created by cmd conduit create db_and_auth is useless.

### ISSUE THREAD

**Issue by MansonLuo** [conduit-dart/conduit#142]
just contain a simple endpoint of /example that return key and values that user entered.

**Comment by j4qfrost** [comment]
This issue is useless. Use better words.

**Comment by j4qfrost** [comment]
Alright I was a bit harsh. The db_and_auth template should have endpoints built in, whatever changed while I was working on the framework must have broken. I haven't had time to run through everything, and I am covering 3 platforms and don't have Windows set up just yet.

**Comment by MansonLuo** [comment]
ok, I know
