### ISSUE TITLE
suggestion to alter cmd 'conduit create db_and_auth'.

### ISSUE THREAD

**Issue by MansonLuo** [conduit-dart/conduit#143]
in introduction, the cmd 'conduit create db_and_auth' should create  An conduit application with a database connection, data model and OAuth 2.0 endpoints.
but actually, this cmd just create a simple project that only contain a simple endpoint /example that return whatever key-value pairs user entered.
so maybe this need to be improved.

**Comment by j4qfrost** [comment]
The point of a simple template is to be able to create minimal unit test conditions. If you want something more extensive, you need to set it up yourself. I have plans to move the templates directory to its own project and add a subcommand for adding custom templates.
