### ISSUE TITLE
[BUG] Documentation page - Page not found

### ISSUE THREAD

**Issue by Mibeon** [conduit-dart/conduit#163]
**Describe the bug**
If you click on the [Docs](https://gitbook.theconduit.dev/), you'll find that there's no valid url actually.
Very unfavorable particularly for new devs 🙄

**To Reproduce**
Just click on the link at [Conduit](https://www.theconduit.dev/)

**Screenshots**
<img width="1285" alt="not-found" src="https://user-images.githubusercontent.com/35590178/210404849-02d50ef8-77a4-4084-971e-08ef0ee69f56.png">

**Comment by Bes79** [comment]
same

**Comment by victor7w7r** [comment]
Another link was [https://docs.theconduit.dev](url) but still not working, i have
`ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

Please help

**Comment by j4qfrost** [comment]
Fixed on README
