### ISSUE TITLE
[BUG] Why does the FOREIGN KEY MUST be unique? We can not insert another row with the same FOREIGN KEY ?

### ISSUE THREAD

**Issue by denghejun** [conduit-dart/conduit#205]
# the below is the output logs when I execute conduit upgrade
 CREATE TABLE _conduit_version_pgsql (versionNumber INT NOT NULL UNIQUE,dateOfUpgrade TIMESTAMP NOT NULL)
    Applying migration version 1...
        CREATE TABLE _Role (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL UNIQUE,modifyDate TIMESTAMP NOT NULL,modifyUserID INT NOT NULL,createDate TIMESTAMP NOT NULL,createUserID INT NOT NULL)
        CREATE INDEX _Role_createDate_idx ON _Role (createDate)
        CREATE TABLE _User (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL UNIQUE,password TEXT NOT NULL,phone TEXT NOT NULL,mail TEXT NULL,modifyDate TIMESTAMP NOT NULL,modifyUserID INT NOT NULL,createDate TIMESTAMP NOT NULL,createUserID INT NOT NULL)
        CREATE INDEX _User_createDate_idx ON _User (createDate)
        **ALTER TABLE _User ADD COLUMN role_id BIGINT NULL UNIQUE** // <-Here! Why this must be unique? 
        CREATE INDEX _User_role_id_idx ON _User (role_id)
        ALTER TABLE ONLY _User ADD FOREIGN KEY (role_id) REFERENCES _Role (id) ON DELETE SET NULL
.... .....

**Comment by victorths** [comment]
You can define it as ` isUnique: false` on the migration
`database.addColumn(
        "_Event",
        SchemaColumn.relationship("post", ManagedPropertyType.bigInteger,
            relatedTableName: "_Post", relatedColumnName: "id", rule: DeleteRule.nullify, isNullable: true, isUnique: false));`

**Comment by denghejun** [comment]
> 

Thank you, can we specify isUnique:false at annotation level? like: 
```
 @Relate(#user, unique: false)
  Role? role;
```

**Comment by victorths** [comment]
You can if you use the `@Column(unique: false) `annotation directly

**Comment by denghejun** [comment]
> You can if you use the `@Column(unique: false) `annotation directly

NO, I cannot add both of `@Relate and @Column at the same time`, if I do  that, I will get an error. Can we enhance this feature like `@Relate(#user, unique: false)`?

**Comment by denghejun** [comment]
Sorry it is my fault, I should set relationship like the below:
```
class _Role extends BaseDBModel {
  @primaryKey
  int? id;

  @Column(nullable: true, unique: true)
  String? name;

  ManagedSet<User>? users;
}
```
