### ISSUE TITLE
[BUG] conduit create reporting that it can't find conduit.

### ISSUE THREAD

**Issue by bsutton** [conduit-dart/conduit#48]
conduit create home

-- Conduit CLI Version: 2.0.0-b9
    Template source is: /home/bsutton/.pub-cache/hosted/pub.dartlang.org/conduit-2.0.0-b9/templates/default/
    See more templates with 'conduit create list-templates'
-- Copying template files to project directory (/home/bsutton/home)...
    Copying contents of /home/bsutton/.pub-cache/hosted/pub.dartlang.org/conduit-2.0.0-b9/templates/default/.gitignore
    Copying contents of /home/bsutton/.pub-cache/hosted/pub.dartlang.org/conduit-2.0.0-b9/templates/default/.travis.yml
    Copying contents of /home/bsutton/.pub-cache/hosted/pub.dartlang.org/conduit-2.0.0-b9/templates/default/config.src.yaml
    Copying contents of /home/bsutton/.pub-cache/hosted/pub.dartlang.org/conduit-2.0.0-b9/templates/default/analysis_options.yaml
    Copying contents of /home/bsutton/.pub-cache/hosted/pub.dartlang.org/conduit-2.0.0-b9/templates/default/pubspec.yaml
    Copying contents of /home/bsutton/.pub-cache/hosted/pub.dartlang.org/conduit-2.0.0-b9/templates/default/bin
    Copying contents of /home/bsutton/.pub-cache/hosted/pub.dartlang.org/conduit-2.0.0-b9/templates/default/lib
    Copying contents of /home/bsutton/.pub-cache/hosted/pub.dartlang.org/conduit-2.0.0-b9/templates/default/test
    Copying contents of /home/bsutton/.pub-cache/hosted/pub.dartlang.org/conduit-2.0.0-b9/templates/default/README.md
    Generating config.yaml from config.src.yaml.
*** We can't find conduit in the pub cache. Check that your PUB_CACHE is set correctly.

**Comment by khalidlionel** [comment]
anything new about this issue?

**Comment by j4qfrost** [comment]
Closing due to recent changes with melos https://github.com/conduit-dart/conduit/pull/71
