### ISSUE TITLE
[BUG] The getter 'haveAtLeastOneWhere' isn't defined

### ISSUE THREAD

**Issue by dbilgin** [conduit-dart/conduit#53]
**Describe the bug**
So I was trying to use the ORM and add relationships between models using [this](https://gitbook.theconduit.dev/db/advanced_queries#including-relationships-in-a-fetch-aka-joins) documentation.
I have the below models:

subject.dart
```
class Subject extends ManagedObject<_Subject> implements _Subject {}

class _Subject {
  @primaryKey
  int? id;

  @Column(nullable: false)
  String? name;

  ManagedSet<SubjectUnit>? subjectUnits;
}
```

subject_unit.dart
```
class SubjectUnit extends ManagedObject<_SubjectUnit> implements _SubjectUnit {}

class _SubjectUnit {
  @primaryKey
  int? id;

  @Relate(#subjectUnits)
  Unit? unit;

  @Relate(#subjectUnits)
  Subject? subject;
}

```

Now basically, I was trying to make a join statement like below:
```
final subjectQuery = Query<Subject>(context)
      ..where((h) => h.subjectUnits?.haveAtLeastOneWhere.unit.id)
          .equalTo(unitId)
      ..join(set: (u) => u.subjectUnits);
```
But when I try to do this, I get the error: `The getter 'haveAtLeastOneWhere' isn't defined for the type 'ManagedSet<SubjectUnit>'.`
I thought I was following the docs properly, but did I miss something here perhaps?

**Comment by j4qfrost** [comment]
It appears that was removed during the wild west days of development by someone else. Sorry for the late response, I will look into this shortly.

**Comment by j4qfrost** [comment]
@dbilgin It looks like support for this was dropped back when the project was under Stablekernel. I will look at this further to see if we need to reimplement this. Can you provide your specific use case just for my edification? Thanks.

**Comment by dbilgin** [comment]
@j4qfrost thank you for your response! my use case was with table relations one-to-many. I have units and under the units I have subjects and every subject can have more than one unit. I wanted to be able to get all the subjects that belong to one unit so I needed to request this `haveAtLeastOneWhere` with the unit id.

**Comment by Reductions** [comment]
@dbilgin It is better to write:
```dart
final subjectQuery = Query<SubjectUnit>(context)
      ..where((su)=> su.unit).idetifiedBy(unitId)
      ..join(set: (su) => su.subject);
```

**Comment by j4qfrost** [comment]
@Reductions nice you see you, how've you been?

**Comment by dbilgin** [comment]
thanks @Reductions
