### ISSUE TITLE
Can't even get started with conduit create [BUG]

### ISSUE THREAD

**Issue by jocubeit** [conduit-dart/conduit#56]
### Listing Templates
```
% conduit create list-templates
```

Results in:
```
-- Conduit CLI Version: 3.0.11
*** Uncaught error
    Bad state: No element
  **** Stacktrace
  * #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
  * #1      CLIConduitGlobal.conduitPackageRef (package:conduit/src/cli/commands/create.dart:388:10)
  * #2      CLIConduitGlobal.templateDirectory (package:conduit/src/cli/commands/create.dart:393:12)
  * #3      CLITemplateList.handle (package:conduit/src/cli/commands/create.dart:341:53)
  * #4      CLICommand.process (package:conduit/src/cli/command.dart:219:20)
  * <asynchronous suspension>
  * #5      main (file:///Users/kodemunki/Development/flutter/.pub-cache/hosted/pub.dartlang.org/conduit-3.0.11/bin/conduit.dart:9:14)
  * <asynchronous suspension>
  ****
```

### Creating Project
```
% conduit create -t db restapi
```

Results in:
```
-- Conduit CLI Version: 3.0.11
*** Uncaught error
    Bad state: No element
  **** Stacktrace
  * #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
  * #1      CLIConduitGlobal.conduitPackageRef (package:conduit/src/cli/commands/create.dart:388:10)
  * #2      CLIConduitGlobal.templateDirectory (package:conduit/src/cli/commands/create.dart:393:12)
  * #3      CLIConduitGlobal.getTemplateLocation (package:conduit/src/cli/commands/create.dart:397:12)
  * #4      CLITemplateCreator.handle (package:conduit/src/cli/commands/create.dart:52:27)
  * #5      CLICommand.process (package:conduit/src/cli/command.dart:219:20)
  * <asynchronous suspension>
  * #6      main (file:///Users/kodemunki/Development/flutter/.pub-cache/hosted/pub.dartlang.org/conduit-3.0.11/bin/conduit.dart:9:14)
  * <asynchronous suspension>
  ****
```

### Desktop
 - OS: `macOS (Big Sur) 11.2 (20D64)`
 - dart: `Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "macos_x64"`
 - flutter: `Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (3 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0`
- zshrc: `
export PATH="$PATH:$HOME/Development/flutter/bin"
export PATH="$PATH":"$HOME/.pub-cache/bin"
export PATH="$PATH":"$HOME/Development/flutter/.pub-cache/bin"`

**Comment by jocubeit** [comment]
Tried creating a brand new user on my mac. Installed flutter and dart, went through the Android hoopla. Flutter doctor says all good. Globally activated conduit. Tried the following:

```
conduit create rest
```

Got:
```         
-- Conduit CLI Version: 3.0.11
*** No template at .
```

Conduit can't find templates. Tried specifying default with -t, but same result.

Any help available here?

**Comment by j4qfrost** [comment]
Can you tell me what your PUB_CACHE environment variable is?

**Comment by jocubeit** [comment]
PUB_CACHE variable is non-existent from command line. If I add a print statement in a dart project I get "null" from Platform.environment. This is on a new installation of flutter/dart for a new macOS user.

**Comment by j4qfrost** [comment]
@jocubeit thanks for your patience. I'll be doing some documentation work and trying to install conduit from a fresh machine to make the installation guide more verbose. Hopefully I can clear up your issue along the way. You wouldn't happen to be on an M1 Mac would you?

**Comment by jocubeit** [comment]
Thanks for getting back to me. I am indeed on an M1, but I also experienced
this on an Intel iMac.

**Comment by outersky** [comment]
It still fails to find template anywhere today.
How can I copy those files manually?

**Comment by aadarshadhakalg** [comment]
@outersky What's the output of ```dart pub global list``` ?

**Comment by outersky** [comment]
@aadarshadhakalg 

```
tony@tonybook:/data/work/dart$ conduit create --stacktrace my_project

-- Conduit CLI Version: 3.0.11
*** No template at .
```

**Comment by j4qfrost** [comment]
For your .zshrc or .profile or whatever you use to load the shell, do ```export PUB_CACHE=/Users/kodemunki/Development/flutter/.pub-cache```

I think it should also be in your PATH. I can help walk you through on discord my handle is frosty#1337, the server is on the README.

**Comment by j4qfrost** [comment]
Closing as there have been a bunch of changes to how everything is structured and there's been no response on the ticket.
