### ISSUE TITLE
[BUG] Postgres 14 (14beta2) not supported by `conduit db upgrade`

### ISSUE THREAD

**Issue by jayjah** [conduit-dart/conduit#59]
Current postgres 14 beta is not supported by `conduit db upgrade`.

**To Reproduce**
1. `conduit create test`

2. Create simple model, therefore a controller and export them

model:
```
import 'package:conduit/conduit.dart';

class Hero extends ManagedObject<_Hero> implements _Hero {}

class _Hero {
  @primaryKey
  late int id;

  @Column(unique: true)
  late String name;
}
```

controller:
```

import 'package:conduit/conduit.dart';
import 'package:server/models/heroe.dart';

class HeroesController extends ResourceController {
  HeroesController(this.context);

  final ManagedContext context;

  @Operation.get()
  Future<Response> getAllHeroes() async {
    final heroQuery = Query<Hero>(context);
    final heroes = await heroQuery.fetch();

    return Response.ok(heroes);
  }
}
``` 

exporting:
```
/// server
///
/// A conduit web server.
library server;

export 'dart:async';
export 'dart:io';

export 'package:conduit/conduit.dart';

export 'channel.dart';
export 'controllers/heroe_controller.dart';
export 'models/heroe.dart';
```

2. Create migration file with: `conduit db generate`

3. Run postgres:14beta2 locally, e.G. ` docker run --name postgres14_test --rm  -e POSTGRES_DB=test -e POSTGRES_PASSWORD=test -e POSTGRES_USER=test -p 5432:5432  -d postgres:14beta2`

4. Run `conduit db upgrade --connect postgres://test:test@localhost:5432/test`

5. See error: 
```
-- Conduit CLI Version: 3.0.11
-- Conduit project version: 3.0.11
*** There was an error connecting to the database 'test:test@localhost:5432/test'. Reason: unable to connect to database.
```

**Expected behavior**
```
-- Conduit CLI Version: 3.0.11
-- Conduit project version: 3.0.11
-- Updating to version 2 on new database...
    PostgreSQL connecting, test@localhost:5432/test.
    Initializating database...
    	CREATE TABLE _conduit_version_pgsql (versionNumber INT NOT NULL UNIQUE,dateOfUpgrade TIMESTAMP NOT NULL)
    Applying migration version 1...
    Seeding data from migration version 1...
    Applied schema version 1 successfully.
    Applying migration version 2...
    	CREATE TABLE _Hero (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL UNIQUE)
    Seeding data from migration version 2...
    Applied schema version 2 successfully.
```

**Desktop (please complete the following information):**
 - OS: macOS BigSur 11.4

**Comment by j4qfrost** [comment]
Is the database using ssl as a default?

**Comment by jayjah** [comment]
@j4qfrost  
Actually no, default `postgresql.conf` for ssl settings looks like the following:

```
#ssl = off
#ssl_ca_file = ''
#ssl_cert_file = 'server.crt'
#ssl_crl_file = ''
#ssl_crl_dir = ''
#ssl_key_file = 'server.key'
#ssl_ciphers = 'HIGH:MEDIUM:+3DES:!aNULL' # allowed SSL ciphers
#ssl_prefer_server_ciphers = on
#ssl_ecdh_curve = 'prime256v1'
#ssl_min_protocol_version = 'TLSv1.2'
#ssl_max_protocol_version = ''
#ssl_dh_params_file = ''
#ssl_passphrase_command = ''
#ssl_passphrase_command_supports_reload = off
```

These settings came from a fresh postgres:14beta2 postgres db.

**Comment by j4qfrost** [comment]
Do you have a db up I can test against?

**Comment by mostafaElspagh0** [comment]
it works fine on my machine 
ubuntu 20.04

**Comment by j4qfrost** [comment]
@mostafaElspagh0 you have postgres 14 installed?

**Comment by mostafaElspagh0** [comment]
could it be it is a mac specific issue ?

**Comment by j4qfrost** [comment]
Aaaa, I wasn't paying attention. It could be. Macs will prompt you for network access, though that should be obvious. It could also be an issue with docker on Mac.

**Comment by jayjah** [comment]
Well, network access is allowed, that's definitely not the case here, but it may relate to an issue with docker on mac. Especially when it works on ubuntu 20.04. I will try it with an ubuntu 20.04 os mostly tomorrow.

**Comment by j4qfrost** [comment]
One way to check is using psql to try to access the db.

**Comment by j4qfrost** [comment]
Can you use postgres 9.6 to see if that works? That way we can narrow it
down to a db on Mac issue or a docker on Mac issue.

**Comment by jayjah** [comment]
Can be closed - as of working now perfectly fine!
