### ISSUE TITLE
WebSocket upgrade not working

### ISSUE THREAD

**Issue by neterror** [conduit-dart/conduit#79]
When trying to upgrade HTTP connection to WebSocket, the following exception is thrown:

[SEVERE] conduit: Failed to send response, draining request. Reason: Bad state: Header already sent  

**To Reproduce**
1. ResourceController handler in conduit
```
    final httpRequest = request?.raw;
    if (httpRequest == null) {
      return Response(400, {}, null); //400 - bad request
    }
    _socket = await WebSocketTransformer.upgrade(httpRequest);
    int counter = 0;
    Stream.periodic(const Duration(seconds: 1)).take(5).listen((event) {
      counter += 1;
      _socket?.add('message ${counter}');
    });

/// the doc says:
/// It's important that a request that is upgraded to a websocket is removed from the channel 
/// by returning null from the controller. 
    return null;
```

2. Client flutter web application invokes
`
 final socket = WebSocketChannel.connect(Uri.parse('ws://localhost:8888/something'));
`

**Expected behavior**
Upgrade to websocket and send 5 messages to the client

**Comment by j4qfrost** [comment]
I've already merged your change, but now with the CI fixed up, would you mind writing a test? I can make an attempt, but it would be nice if I had some help.

**Comment by neterror** [comment]
Thank you! I'll write some unit tests
