### ISSUE TITLE
Double where query[BUG]

### ISSUE THREAD

**Issue by justintim-es** [conduit-dart/conduit#81]
Hi how do we do a double where query, i have the following query 
```        
final isDecryptorFollowing = Query<Following>(context)
          ..where((i) => i.follower?.id).equalTo(request!.authorization!.ownerID)
          ..where((i) => i.chatter?.id).equalTo(follow.follower?.id);
```
 but if one out of the 2 satisfies it does return a value but i only want a result if they both satisfy, can anyone help me?

**Comment by neterror** [comment]
Can you post the models as well. I can't reproduce the problem - the double where clauses have correct behavior. Both of them must match to select the row. It may be something related to the optional values.

**Comment by j4qfrost** [comment]
@justintim-es to debug test each where clause individually and show results also as neterror suggested provide the models and as much code as you can. Reopen if you still have the same issues. Also upgrade to the latest version.
