### ISSUE TITLE
[BUG] conduit create not working on Windows

### ISSUE THREAD

**Issue by Archiware** [conduit-dart/conduit#92]
**Describe the bug**
When trying to use conduit from PowerShell 7.2.4 on Windows 11, the "create" method does not seem to work out of the box. (I assume some sort of path issue, as always when trying to code on Windows.)

Here's the console output:
```
PS D:\Home\Git> conduit create waid_server
-- Conduit CLI Version: 3.1.2
*** No template at .
```

I wasn't bothering much with trying to fix it, as I could simply install conduit in my Ubuntu on Bash on Windows and create the project from within that, but that should be looked into at some point, I think.

**Comment by andresruizdev** [comment]
Hello @Archiware 

I had the same problem before, I think that is not produced by a bug in the conduit source or problems with the Windows version (I have Windows 11 too).

Please try to use the command `pub global activate conduit` again (This works for me some days ago), specially if you changed your Dart or Flutter version. This will happen too if you changed the value of **PUB_CACHE Environment Value**

If the command is not working after use the previous instruction, use the command explicitly according to your Dart or Flutter SDK console functions with the conduit arguments. Example: `flutter pub global run conduit create waid_server` for Flutter or `pub global run conduit create waid_server` for Dart.

If this two options is not working for you, please check releated issues: #48 and #56 .

Now I can create proyects as you can see in the following lines:

**Before**
```
C:\Users\SistemasC\Documents\test1>conduit create wrpa
-- Conduit CLI Version: 3.1.2
*** No template at .
```

**After**
```
C:\Users\SistemasC\Documents\test1>conduit create wrpa45
-- Conduit CLI Version: 3.1.2
    Template source is: C:\flutter\.pub-cache\bin\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\
    See more templates with 'conduit create list-templates'
-- Copying template files to project directory (C:\Users\SistemasC\Documents\test1\wrpa45)...
    Copying contents of C:\flutter\.pub-cache\bin\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\analysis_options.yaml
    Copying contents of C:\flutter\.pub-cache\bin\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\bin
    Copying contents of C:\flutter\.pub-cache\bin\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\config.src.yaml
    Copying contents of C:\flutter\.pub-cache\bin\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\lib
    Copying contents of C:\flutter\.pub-cache\bin\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\pubspec.yaml
    Copying contents of C:\flutter\.pub-cache\bin\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\README.md
    Copying contents of C:\flutter\.pub-cache\bin\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\test
    Generating config.yaml from config.src.yaml.
-- Fetching project dependencies (pub get )...
-- Please wait...
Resolving dependencies...
+ _fe_analyzer_shared 22.0.0 (40.0.0 available)
+ analyzer 1.7.2 (4.1.0 available)
+ args 2.3.1
+ async 2.9.0
+ boolean_selector 2.1.0
+ buffer 1.1.1
+ cli_util 0.3.5
+ collection 1.16.0
+ conduit 3.1.2
+ conduit_codable 3.1.1
+ conduit_common 3.1.1
+ conduit_config 3.1.1
+ conduit_isolate_exec 3.1.1
+ conduit_open_api 3.1.1
+ conduit_password_hash 3.1.1
+ conduit_runtime 3.1.1
+ conduit_test 3.1.2
+ convert 3.0.1
+ coverage 1.0.3 (1.3.2 available)
+ crypto 3.0.2
+ file 6.1.2
+ frontend_server_client 2.1.3
+ glob 2.0.2
+ http_multi_server 3.2.0
+ http_parser 4.0.1
+ io 1.0.3
+ js 0.6.4
+ logging 1.0.2
+ matcher 0.12.11
+ meta 1.8.0
+ mime 1.0.2
+ node_preamble 2.0.1
+ package_config 2.0.2
+ path 1.8.2
+ pedantic 1.11.1
+ pool 1.5.0
+ postgres 2.4.3
+ pub_cache 0.3.1
+ pub_semver 2.1.1
+ pubspec 2.1.0
+ quiver 3.1.0
+ sasl_scram 0.1.0
+ saslprep 1.0.2
+ shelf 1.3.0
+ shelf_packages_handler 3.0.0
+ shelf_static 1.1.0
+ shelf_web_socket 1.0.1
+ source_map_stack_trace 2.1.0
+ source_maps 0.10.10
+ source_span 1.9.0
+ stack_trace 1.10.0
+ stream_channel 2.1.0
+ string_scanner 1.1.1
+ term_glyph 1.2.0
+ test 1.18.1 (1.21.1 available)
+ test_api 0.4.5 (0.4.9 available)
+ test_core 0.4.4 (0.4.13 available)
+ typed_data 1.3.1
+ unorm_dart 0.2.0
+ uri 1.0.0
+ vm_service 7.5.0 (8.3.0 available)
+ watcher 1.0.1
+ web_socket_channel 2.2.0
+ webkit_inspection_protocol 1.1.0
+ yaml 3.1.1
Changed 65 dependencies!
    Success.
-- project 'wrpa45' successfully created.
    Project is located at C:\Users\SistemasC\Documents\test1\wrpa45
    Open this directory in IntelliJ IDEA, Atom or VS Code.
    See C:\Users\SistemasC\Documents\test1\wrpa45\README.md for more information.
```

**Comment by RicardoRB** [comment]
I tried yesterday as first time installation and I didn't find any kind of problem following the "Get Started" article (https://www.theconduit.dev/start/).

I just needed to add the bin in my window's path.

**Comment by andresruizdev** [comment]
> I tried yesterday as first time installation and I didn't find any kind of problem following the "Get Started" article (https://www.theconduit.dev/start/).
> 
> I just needed to add the bin in my window's path.

Let me check... I' going to create a clean Virtual Machine Instance to follow the documentation from scratch.

**Comment by andresruizdev** [comment]
Hello @Archiware and @RicardoRB .

After a long check in a completely new and clean Windows 11 instance (I tried in Windows 10 too). I installed Conduit and created some projects successfully. Please check your develompent environment.

# Followed Steps:

### 1. Install Windows 11 (Latest Version from Microsoft Site)
### 2. Complete First Step Assistant and Create Main Windows User
### 3. Open PowerShell as Administrator
### 4. Get ExecutionPolicy Value with `Get-ExecutionPolicy` command
```
PS C:\Users\ConduitTest> Get-ExecutionPolicy
Restricted
```
### 5. Execution Policy modified by command `Set-ExecutionPolicy Bypass -Scope Process`
### 6. Install Chocolatey 
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```
### 7. Restart PowerShell (To update Environment variables) and then install dart-sdk after check that choco command is working
```
PS C:\Users\ConduitTest> choco --version
1.1.0
```

**NOTE:** I used the commands that Conduit have in Official Documentation
```
:: (in an administrator command line)
choco install dart-sdk
:: Test that it works - display version string
dart --version
```

#### Results of `dart --version`

```
dart --version
Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "windows_x64"
```
### 8. Path Problems
At this moment, I notice that after install dart-sdk `pub` is not recognized as a command. I found that `choco` do not add the correct Path for Pub Cache Values.

#### Path Added by choco
```
C:\Users\ConduitTest\AppData\Roaming\Pub\Cache\bin
```

#### Path of real Pub Cache Folder after SDK installation
```
C:\Users\ConduitTest\AppData\Local\Pub\Cache\bin
```
#### Temporal and Fast Solution
So after I saw this, I updated the correct Path and restart PowerShell (pub not working yet for me so, I decide to use `dart pub global activate conduit` instead only `pub` and it works). This only grant that pub apps commands will be used by your system, I guess.

### 9. Check conduit version
After use `dart pub global activate conduit` I check the conduit version as it is recommended in the documentation (After change Pub Path this should work).

```
PS C:\Users\ConduitTest> conduit --version                                                                                   
Conduit CLI version: 3.1.2 
```

### 10. Create the project
Finally I create the project and... It's working :C

```
conduit create test_project
-- Conduit CLI Version: 3.1.2
    Template source is: C:\Users\ConduitTest\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\
    See more templates with 'conduit create list-templates'
-- Copying template files to project directory (C:\Users\ConduitTest\Documents\dart\test_project)...
    Copying contents of C:\Users\ConduitTest\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\analysis_options.yaml
    Copying contents of C:\Users\ConduitTest\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\bin
    Copying contents of C:\Users\ConduitTest\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\config.src.yaml
    Copying contents of C:\Users\ConduitTest\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\lib
    Copying contents of C:\Users\ConduitTest\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\pubspec.yaml
    Copying contents of C:\Users\ConduitTest\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\README.md
    Copying contents of C:\Users\ConduitTest\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\conduit-3.1.2\templates\default\test
    Generating config.yaml from config.src.yaml.
-- Fetching project dependencies (pub get )...
-- Please wait...
Resolving dependencies...

...

Changed 65 dependencies!                                                                                                   
Success.
project 'test_project' successfully created.
Project is located at C:\Users\ConduitTest\Documents\dart\test_project
Open this directory in IntelliJ IDEA, Atom or VS Code.
See C:\Users\ConduitTest\Documents\dart\test_project\README.md for more information.
```

**Comment by RicardoRB** [comment]
Good to hear! Should this issue be closed? 🤔

**Comment by j4qfrost** [comment]
I have made major changes to the project so this should be stale, will be improving contribution and getting started next
